# ==================================================
# Sheldon plugins
# Load Zsh plugins and initialize completion in the required order.
# ==================================================

shell = "zsh"

[plugins]

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit'

[plugins.fzf-tab]
github = 'Aloxaf/fzf-tab'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
